### ISSUE TITLE
FR: Setting block title from frontmatter

### ISSUE THREAD

**Issue by marconoris** [javierarce/arena-manager#3]
Hi Javier,

another FR: the possibility of changing/setting the title of the block through the frontmatter. Isn't so important but could be useful?

Thanks!!

**Comment by javierarce** [comment]
This is a good idea because there are cases where a channel could contain blocks with the same name (e.g.: Title.md, Title.md, Title.md). 

To be able to save them locally, I'm adding a number to the end of the filename (e.g.: Title.md, Title-1.md, Title-2.md, etc.). However, this means that if you push the note back to Are.na, you'll be updating the block's title with the numbered filename, which would be bad.

Thanks for the suggestion!

**Comment by javierarce** [comment]
I've included this fix into the [1.0.4](https://github.com/javierarce/arena-manager/releases/tag/1.0.4) release, so I'm closing this issue.
